CoderDojoParis/urls.py
from django.contrib import admin
from django.urls import path, include

from Core import views

urlpatterns = [
    path('', include('Homepage.urls')),  # Include the urls of the Hompage module at the root
    path('', include('Core.urls')),  # Include Core module
    path('dashboard/', include('Dashboard.urls')),
    path('admin/', admin.site.urls),
]

handler400 = views.BadRequestError
handler404 = views.NotFoundError
handler403 = views.PermissionDeniedError
handler500 = views.ServerError

Core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('login/', views.loginview, name='login'),
    path('adminlogin/', views.adminlogin, name='admin-login'),
    path('logout/', views.logout_request, name='logout'),
]

Homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),  # Landing page
    path('events/', views.events, name='events'),  # List of the events
    path('staff/', views.staff, name='staff'),  # List of the staff
    path('about/', views.about, name='about'),  # More about the association
]

Homepage/models.py
# Create your models here.
from django.db import models


class SliderImage(models.Model):
    url = models.URLField()
    title = models.CharField(max_length=50)
    text = models.CharField(max_length=200)

    def __str__(self):
        return "Image : %s " % self.title


class Text(models.Model):
    type = models.CharField(max_length=100, unique=True)
    title = models.CharField(max_length=100, blank=True)
    text = models.TextField()

    def __str__(self):
        return "Text %s pour %s " % (self.type, self.title)

Homepage/forms.py
from django import forms
from .models import Text, SliderImage
from Dashboard.models import Mail


class EmailForm(forms.ModelForm):
    class Meta:
        model = Mail
        fields = ['subject', 'content']
        labels = {
            'subject': 'Sujet',
            'content': 'Contenu',
        }
        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Sujet'}),
            'content': forms.Textarea(attrs={'id': 'ckeditor', 'class': 'form-control', 'placeholder': 'Contenu'}),
        }


class TextForm(forms.ModelForm):
    class Meta:
        model = Text
        fields = ['title', 'text']
        labels = {
            'title': 'Titre',
            'text': 'Contenu',
        }
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Titre'}),
            'text': forms.Textarea(attrs={'id': 'ckeditor', 'class': 'form-control', 'placeholder': 'Contenu'}),
        }


class ImageForm(forms.ModelForm):
    class Meta:
        model = SliderImage
        fields = ['url', 'title', 'text']
        labels = {
            'url': "Lien de l'Image",
            'title': 'Titre',
            'text': 'Description',
        }
        widgets = {
            'url': forms.URLInput(attrs={'class': 'form-control', 'placeholder': "Lien de l'image"}),
            'title': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Titre'}),
            'text': forms.Textarea(attrs={'id': 'ckeditor', 'class': 'form-control', 'placeholder': 'Contenu'}),
        }

Homepage/views.py
import datetime

from django.shortcuts import render
from django.utils import timezone

from Core.models import Event, User
from .models import Text, SliderImage

"""
Controller of the Hompage module
The absolute folder of the templates rendered here : ./templates/Homepage/fileName.html
"""


def index(request):  # Landing page
    images = None
    try:
        images = SliderImage.objects.all()
    except SliderImage.DoesNotExist:
        pass
    return render(request, 'Homepage/homepage.html', setReturnedValues(request, {'images': images,
                                                                                 'ints': range(
                                                                                     images.count())}))


def events(request):  # List of events
    return render(request, 'Homepage/events.html',
                  setReturnedValues(request, {
                      'events': Event.objects.filter(time_from__gte=datetime.datetime.now(tz=timezone.utc))}))


def staff(request):  # List of Staff
    return render(request, 'Homepage/staff.html',
                  setReturnedValues(request, {'staff': User.objects.filter(type='STA')}))


def about(request):  # More about the association
    data = {}
    try:
        data['where'] = Text.objects.get(type='where')
    except Text.DoesNotExist:
        pass
    try:
        data['joinus'] = Text.objects.get(type='joinus')
    except Text.DoesNotExist:
        pass
    try:
        data['whatis'] = Text.objects.get(type='whatis')
    except Text.DoesNotExist:
        pass
    return render(request, 'Homepage/about.html', setReturnedValues(request, data))


def setReturnedValues(request, args=None):
    user = request.user
    if 'notifications' in request.session:
        notif = request.session['notifications']
        request.session['notifications'] = []
    else:
        notif = []

    default_data = {}
    try:
        default_data['footer'] = Text.objects.get(type='footer')
    except Text.DoesNotExist:
        pass

    data = default_data.copy()
    if args:
        data.update(args)
    return data

Homepage/templates/Homepage/events.html
{% extends 'Homepage/layout.html' %}

{% block title %}Evènements{% endblock %}

{% block body %}
    <h1>Events Futurs</h1>
    <ul>
    {% for event in events %}
        <li><h3>{{ event.time_from|date|title }}</h3> {{ event.public_adress|title }}</li>
        <hr>
    {% endfor %}
    </ul>
{% endblock %}

Homepage/templates/Homepage/footer.html
<section id="footer">
    <div class="container">
        <div class="row text-center text-xs-center text-sm-left text-md-left">
            <div class="col-xs-12 col-sm-4 col-md-4">
                <h5>Quick links</h5>
                <ul class="list-unstyled quick-links">
                    <li><a href="{% url 'homepage:index' %}"><i class="fas fa-home"></i>Accueil</a></li>
                    <li><a href="{% url 'homepage:events' %}"><i class="far fa-calendar-alt"></i>Evènements</a></li>
                    <li><a href="{% url 'homepage:staff' %}"><i class="fas fa-users"></i>L'équipe</a>
                    </li>
                    <li><a href="{% url 'homepage:about' %}"><i class="fas fa-info"></i>En savoir plus</a>
                    </li>
                </ul>
            </div>
            <div class="col-xs-12 col-sm-4 col-md-8">
                {% if footer is not None %}
                    <h5>{{ footer.title }}</h5>
                    {{ footer.text|safe }}
                {% else %}
                    <h5>CoderDojo?</h5>
                    <p><span>CoderDojo is a global volunteer-led community of free programming clubs for young people between 7 and 17. The movement is a grassroots organisation with individual clubs (called "Dojos") acting independently. A charity called the CoderDojo Foundation operates out of Dublin and supports the various clubs by providing a central website and some other support services. Supporters of CoderDojo believe it is part of the solution to addressing the global shortage of programmers by exposing young people to ICT at a young age. The movement has seen significant growth since its founding. The CoderDojo Foundation estimates 1,250 Dojos spread across 69 countries, with a growth rate of several new Dojos every week.</span>
                    </p>
                {% endif %}
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-5">
                <ul class="list-unstyled list-inline social text-center">
                    <li class="list-inline-item"><a href="https://www.twitter.com/CoderDojoParis"><i
                            class="fab fa-twitter"></i></a>
                    </li>
                    <li class="list-inline-item"><a href="mailto:paris.fr@coderdojo.com" target="_blank"><i
                            class="fa fa-envelope"></i></a></li>
                </ul>
            </div>
            <hr>
        </div>
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 mt-2 mt-sm-2 text-center text-white">
                <p><u><a href="http://coderdojoparis.com/">CoderDojo Paris</a></u></p>
                <p class="h6">&copy All right Reversed.</p>
            </div>
            <hr>
        </div>
    </div>
</section>

Homepage/templates/Homepage/homepage.html
{% extends 'Homepage/layout.html' %}
{% load static %}
{% block title %}Accueil{% endblock %}
{% block body %}
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            {% if ints %}
                    {% for int in ints %}
                        <li data-target="#carouselExampleIndicators" data-slide-to="{{ int }}" {% if int == 0 %}class="active"{% endif %}></li>
                    {% endfor %}
            {% else %}
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            {% endif %}
        </ol>
        <div class="carousel-inner">
            {% if images %}
                {% for image in images %}
                    <div class="carousel-item {% if image.id == images.0.id %}active{% endif %}">
                        <img class="d-block w-100 slider-image" src="{{ image.url }}" alt="First slide">
                        <div class="carousel-caption d-none d-md-block">
                            <h5>{{ image.title }}</h5>
                            {{ image.text|safe }}
                        </div>
                    </div>
                {% endfor %}
            {% else %}
                <div class="carousel-item active">
                    <img class="d-block w-100 slider-image" src="https://placehold.it/1900x1080" alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Title1</h5>
                        <p>This is a pretty long description that could be edited</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 slider-image" src="https://placehold.it/1900x1080"
                         alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Title2</h5>
                        <p>This is a pretty long description that could be edited</p>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100 slider-image" src="https://placehold.it/1900x1080" alt="Third slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h5>Title3</h5>
                        <p>This is a pretty long description that could be edited</p>
                    </div>
                </div>
            {% endif %}
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
{% endblock %}

Homepage/templates/Homepage/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %} - CoderDojo Paris</title>
    <link rel="icon" href="{% static "Homepage/img/favicon.ico" %}"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "Homepage/css/homepage.css" %}">
    <link rel="stylesheet" href="{% static "Homepage/css/footer.css" %}">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.css" rel="stylesheet">
    {% block css %}
    {% endblock %}
</head>
<body>
<div class="main-container">
    {% block navbar %}
        {% include 'Homepage/navbar.html' %}
    {% endblock %}
    {% block body %}
    {% endblock %}
    {% block footer %}
        {% include 'Homepage/footer.html' %}
    {% endblock %}
    {% block js %}
    {% endblock %}
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/noty/3.1.4/noty.min.js"></script>
<script src="{% static 'Core/js/noty.js' %}"></script>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script><script>
    (function ($) {

        {% if notifications %}
            {% for notification in notifications %}
                console.log('{{ notification.type }}');

                new Noty({
                    text: '{{ notification.text }}',
                    type: '{{ notification.type }}'
                }).show();
            {% endfor %}
        {% endif %}
    })(jQuery)
</script>
</body>
</html>

Homepage/templates/Homepage/navbar.html
<nav class="navbar navbar-expand-lg navbar-light navbar-bg">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarText">
        <ul class="nav justify-content-center">
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'homepage:index' %}">Accueil</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:events' %}">Events</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:staff' %}">Staff</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'homepage:about' %}">A Propos</a>
            </li>
        </ul>
    </div>
    <span class="navbar-text">
      <ul class="nav justify-content-end">
          <li class="nav-item">
              <a href="{% url 'core:login' %}" class="nav-link nav-link-end">Mon Compte</a>
          </li>
      </ul>
    </span>
</nav>

Homepage/templates/Homepage/staff.html
{% extends 'Homepage/layout.html' %}

{% block title %}Staff{% endblock %}

{% block body %}
    <h1>Staff</h1>
    <ul>
    {% for personal in staff %}
        <li><h3>{{ personal.get_full_name }}</h3></li>
    {% endfor %}
    </ul>
{% endblock %}