CoderDojoParis/urls.py
from django.contrib import admin
from django.urls import path, include

from Core import views

urlpatterns = [
    path('', include('Homepage.urls')),  # Include the urls of the Hompage module at the root
    path('', include('Core.urls')),  # Include Core module
    path('dashboard/', include('Dashboard.urls')),
    path('admin/', admin.site.urls),
]

handler400 = views.BadRequestError
handler404 = views.NotFoundError
handler403 = views.PermissionDeniedError
handler500 = views.ServerError

Core/urls.py
from django.urls import path

from . import views

app_name = 'core'
urlpatterns = [
    path('login/', views.loginview, name='login'),
    path('adminlogin/', views.adminlogin, name='admin-login'),
    path('logout/', views.logout_request, name='logout'),
]

Dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'
urlpatterns = [
    path('', views.index, name='index'),  # Landing page
    path('events/<int:id>/', views.eventView, name='event'),
    path('events/add/', views.addEvent, name='add-event'),
    path('events/past/', views.pastEvents, name='past-events'),
    path('events/futur/', views.futurEvents, name='futur-events'),
    path('workshop/<int:id>/', views.workshops, name='workshops'),
    path('workshop/add/', views.addWorkshop, name='add-workshop'),
    path('user/<int:id>/', views.userShow, name='user'),
    path('user/edit/<int:id>/', views.editUser, name='user-edit'),
    path('user/delete/<int:id>', views.userDelete, name='user-delete'),
    path('family/', views.families, name='families'),
    path('family/add/', views.addMember, name='add-member'),
    path('family/edit/<int:id>/', views.editFamily, name='edit-family'),
    path('family/<int:id>/', views.families, name='family'),
    path('invite/add/', views.sendInvitation, name='new-invite'),
    path('invite/', views.invitations, name='invitations'),
    path('register/<int:id>/', views.register, name='register'),
    path('invited/<token>/', views.invited, name='invited'),
    path('edition/', views.adminEdition, name='edition-list'),
    path('edition/<type>/<int:id>/', views.adminEdition, name='edition-item'),
]

Homepage/urls.py
from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
    path('', views.index, name='index'),  # Landing page
    path('events/', views.events, name='events'),  # List of the events
    path('staff/', views.staff, name='staff'),  # List of the staff
    path('about/', views.about, name='about'),  # More about the association
]

Core/models/organisation.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
import requests


class Event(models.Model):
    time_from = models.DateTimeField(unique=True)
    time_end = models.DateTimeField(unique=True)
    public_adress = models.CharField(max_length=120)
    adress = models.CharField(max_length=120)
    max_students = models.IntegerField(default=30)
    coordinates = models.CharField(max_length=100, blank=True)  # xxxxxxxxx:yyyyyyyyy for OpenStreetMap
    participants = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True)
    twitter = models.URLField(blank=True)

    STATES = (
        ('PLA', 'Planned'),
        ('REG', 'Registration'),
        ('PRO', 'In Progress'),
        ('FIN', 'Finished')
    )

    state = models.CharField(
        choices=STATES,
        max_length=3,
        default='PLA'
    )

    def save(self, *args, **kwargs):
        api_response = requests.get(
            'https://maps.googleapis.com/maps/api/geocode/json?address={0}&key={1}'.format(self.adress,
                                                                                           settings.GOOGLE_API))
        api_response_dict = api_response.json()
        if api_response_dict['status'] == 'OK':
            latitude = api_response_dict['results'][0]['geometry']['location']['lat']
            longitude = api_response_dict['results'][0]['geometry']['location']['lng']
            self.coordinates = "%s : %s" % (longitude, latitude)
        else:
            raise ValidationError("API error : %s" % api_response_dict)

        if self.time_from >= self.time_end:
            raise ValidationError("La fin est avant le début??")
        super().save(*args, **kwargs)

    def get_coord(self):
        return self.coordinates.split(' : ')

    def __str__(self):
        return "Event du %s / %s " % (self.time_from.day, self.time_from.month)


class Workshop(models.Model):
    name = models.CharField(max_length=20, unique=True)
    description = models.TextField()
    manager = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)

    LEVEL = (
        (1, 'Starter'),
        (2, 'Medium'),
        (3, 'Hard'),
    )

    level = models.IntegerField(
        choices=LEVEL,
        default=1
    )

    def __str__(self):
        return self.name

    def clean(self):
        if self.manager.type != 'STA':
            raise ValidationError("Le manager doit être Staff")

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Ateliers"

Core/models/users.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import EmailValidator, ValidationError
from django.db import models

from Core.models import Workshop


class Family(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=100, unique=True)

    def __str__(self):
        count = 0
        try:
            persons = User.objects.filter(family=self)
            count = persons.count()
        except User.DoesNotExist:
            pass
        return "Famille %s (%s personnes)" % (self.name, count)

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "Familles"

    def get_number(self):
        count = 0
        try:
            persons = User.objects.filter(family=self)
            count = persons.count()
        except User.DoesNotExist:
            pass
        return count


class Invitation(models.Model):
    token = models.UUIDField(unique=True, editable=False)
    date = models.DateTimeField(auto_now=True)
    sender = models.ForeignKey(Family, on_delete=models.CASCADE)
    receiver = models.EmailField(max_length=100, unique=True)
    message = models.TextField(max_length=1500)
    STATES = (
        ('S', 'Sent'),
        ('D', 'Done'),
    )
    state = models.CharField(
        choices=STATES,
        max_length=1,
        default='S'
    )

    def __str__(self):
        return "Pour %s par %s" % (self.receiver, self.sender.name)

    class Meta:
        ordering = ('receiver',)
        verbose_name_plural = "Invitations"


class UserManager(BaseUserManager):
    def create_user(self, name, familyname, type='STU', gender='M', email=None, password=None, super=False, staff=False):
        if familyname is not Family:
            try:
                family = Family.objects.get(name=familyname)
            except Family.DoesNotExist:
                if email is None:
                    raise ValueError('Vous devez fournir une adresse mail afin de créér le compte famille')
                family = Family(name=familyname, email=self.normalize_email(email))
                family.save()

        else:
            family = familyname

        user = self.model(username=name.title(), family=family, type=type, gender=gender)
        user.is_staff = staff
        user.is_superuser = super
        if email is None:
            user.email = family.email
        else:
            user.email = email

        if password is None:
            user.set_unusable_password()
        else:
            user.set_password(password)

        try:
            EmailValidator()(user.email)
        except ValidationError:
            raise ValueError('Adresse Email invalide, veuillez en saisir une valide!')
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password, email, **other_fields):
        self.create_user(name=username, familyname='Temp', email=email, type='STA', password=password, super=True, staff=True)


class User(AbstractUser):  # Participant

    last_name = None
    first_name = None
    username = models.CharField(max_length=150)
    family = models.ForeignKey(Family, on_delete=models.CASCADE)
    registered_workshop = models.ForeignKey(Workshop, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    email = models.EmailField(null=True, blank=True, default=None)

    PARTICIPANT_TYPES = (
        ('STU', 'Participant'),
        ('ADU', 'Adulte'),
        ('STA', 'Mentor'),
    )

    type = models.CharField(
        max_length=3,
        choices=PARTICIPANT_TYPES,
        default='STU'
    )

    GENDER = (
        ('M', 'Homme'),
        ('F', 'Femme')
    )

    gender = models.CharField(
        max_length=1,
        choices=GENDER,
        default=None,
        null=True
    )

    objects = UserManager()

    def __str__(self):
        return "%s %s (%s)" % (self.username, self.family.name, self.get_type_display())

    def get_short_name(self):
        return "%s %s" % (self.username, self.family.name[:1])

    def get_full_name(self):
        return "%s %s" % (self.username, self.family.name)

    class Meta:
        ordering = ('username',)
        verbose_name_plural = "Participants"

Dashboard/models.py
from django.db import models

# Create your models here.

class Mail(models.Model):
    type = models.CharField(max_length=100, unique=True)
    subject = models.CharField(max_length=200)
    content = models.TextField()

    def __str__(self):
        return "Mail : %s" % self.type.title()

Dashboard/forms.py
from django import forms
from Core.models import User, Invitation, Family, Event, Workshop


class EditUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'type', 'gender']
        labels = {
            'username': 'Prénom',
            'type': 'Type',
            'gender': 'Sexe',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prénom'}),
            'type': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Type'}),
            'gender': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Sexe'}),
        }


class AddMember(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'type', 'gender']
        labels = {
            'username': 'Prenom',
            'email': 'Adresse E-Mail',
            'type': 'Type',
            'gender': 'Sexe',
        }
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Prénom'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Adresse E-Mail'}),
            'type': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Type'}),
            'gender': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Sexe'}),
        }


class SendInvitation(forms.ModelForm):
    class Meta:
        model = Invitation
        fields = ['receiver', 'message']
        labels = {
            'receiver': 'Adresse Mail du destinataire',
            'message': 'Message Personalisé',
        }
        widgets = {
            'receiver': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Adresse E-Mail'}),
            'message': forms.Textarea(attrs={'class': 'textarea form-control', 'placeholder': 'Message Personalisé '
                                                                                              'pour accompagner votre'
                                                                                              ' invitation'}),
        }

    def clean(self):
        cleaned = self.cleaned_data
        email = cleaned['receiver']
        message = cleaned['message']

        try:
            family = Family.objects.get(email=email)
            user = User.objects.filter(email=email)
        except(Family.DoesNotExist, User.DoesNotExist):
            pass
        else:
            raise forms.ValidationError('Une famille ou un utilisateur est déjà inscrit avec cette adresse')

        try:
            invitation = Invitation.objects.get(receiver=email)
        except Invitation.DoesNotExist:
            pass
        else:
            raise forms.ValidationError('une invitation à déjà été envoyée à cette adresse')

        return self.cleaned_data


class InvitedFamily(forms.ModelForm):
    family = forms.CharField(label='Nom de Famille',
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control', 'placeholder': 'Nom de votre Famille'}))

    class Meta:
        model = User
        fields = ['email', 'username', 'type', 'gender']
        labels = {
            'email': 'Adresse Mail de contact',
            'username': 'Prénom',
            'type': 'Type',
            'gender': 'Sexe'
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Adresse E-Mail'}),
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Votre Prénom'}),
            'type': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Type'}),
            'gender': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Sexe'}),
        }


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ['time_from', 'time_end', 'public_adress', 'adress', 'max_students', 'participants', 'state',
                  'twitter']
        labels = {
            'time_from': "Heure de début",
            'time_end': "Heure de fin",
            'public_adress': 'Adresse Publique',
            'adress': 'Adresse Privée',
            'max_students': 'Nombre Maximal de Participants',
            'participants': 'Préinscription',
            'state': 'Etat',
            'twitter': 'Lien de la publication Twitter (Vide si pas encore posté!)',
        }
        widgets = {
            'time_from': forms.TextInput(
                attrs={'class': 'form-control datepicker', 'placeholder': 'Heure de Début'}),
            'time_end': forms.TextInput(
                attrs={'class': 'form-control datepicker', 'placeholder': 'Heure de Fin'}),
            'public_adress': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adresse Publique'}),
            'adress': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adresse Privée'}),
            'max_students': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Nombre de participants'}),
            'participants': forms.SelectMultiple(attrs={'class': 'form-control', 'placeholder': 'Préinscrits'}),
            'state': forms.Select(attrs={'class': 'form-control', 'placeholder': 'Etat'}),
            'twitter': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Lien de la publication Twitter'}),
        }


class EditFamily(forms.ModelForm):
    class Meta:
        model = Family
        fields = ['email', 'name']
        labels = {
            'email': 'Adresse E-Mail',
            'name': 'Nom de Famille',
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Adresse E-Mail'}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nom de Famille'}),
        }


class WorkshopForm(forms.ModelForm):
    class Meta:
        model = Workshop
        fields = ['name', 'manager', 'description', 'level']
        labels = {
            'manager': "Responsable de l'Atelier",
            'name': "Nom de l'Atelier",
            'description': "Description de l'Atelier",
            'level': "Niveau de difficulté"
        }
        widgets = {
            'manager': forms.Select(attrs={'class': 'form-control', 'placeholder': "Responsable de l'Atelier"}),
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': "Nom de l'Atelier"}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': "Description de l'Atelier"}),
            'level': forms.Select(attrs={'class': 'form-control', 'placeholder': "Niveau de difficulté"}),
        }

Dashboard/templates/Dashboard/families.html
{% extends 'Dashboard/layout.html' %}
{% block css %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'Dashboard/css/dataTables.bootstrap.min.css' %}">

{% endblock %}
{% block body %}

    <div class="box">
        <div class="box-header with-border">
            <h3>Liste des familles </h3>
        </div>
        <div class="box-body">
            <table id="familytable" class="table table-bordered table-hover">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Nombre de Participants</th>
                    <th>Editer</th>
                </tr>
                </thead>
                <tbody>
                {% for familly in families %}
                    <tr>
                        <td><a href="{% url 'dashboard:family' familly.id %}">{{ familly.id }}</a></td>
                        <td>{{ familly.name }}</td>
                        <td>{{ familly.get_number }}</td>
                        <td><a href="{% url 'dashboard:edit-family' familly.id %}"><span class="badge bg-green"><i
                                class="fa fa-edit"></i></span></a></td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    </div>
{% endblock %}
{% block scritps %}
    {% load static %}
    <script src="{% static 'Dashboard/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'Dashboard/js/dataTables.bootstrap.min.js' %}"></script>
    <script>
        $(function () {
            $('#familytable').DataTable()
        })
    </script>
{% endblock %}

Dashboard/templates/Dashboard/family.html
{% extends 'Dashboard/layout.html' %}
{% block body %}
    <div class="box box-success">
        <div class="box-header with-border"><h3>{{ selected_family }}</h3></div>
        <div class="box-body">
            <div class="table-responsive">
                <table class="table no-margin">
                    <thead>
                    <tr>
                        <th>Id</th>
                        <th>Prénom</th>
                        <th>Sexe</th>
                        <th>Connecter</th>
                        <th>Editer</th>
                        <th>Supprimer</th>
                    </tr>

                    </thead>
                    <tbody>
                    {% for familyUser in users %}
                        <tr>
                            <td>{{ familyUser.id }}</td>
                            <td>{{ familyUser.username }}</td>
                            <td>{{ familyUser.get_gender_display }}</td>
                            <td><a href="{% url 'dashboard:user' familyUser.id %}"><span class="badge bg-blue"><i
                                    class="fa fa-sign-in"></i></span></a></td>
                            <td><a href="{% url 'dashboard:user-edit' familyUser.id %}"><span class="badge bg-green"><i
                                    class="fa fa-edit"></i></span></a></td>
                            <td><a href="{% url 'dashboard:user-delete' familyUser.id %}"><span class="badge bg-red"><i
                                    class="fa fa-trash"></i></span></a></td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}

Dashboard/templates/Dashboard/header.html
<header class="main-header">
    <a href="{% url 'homepage:index' %}" class="logo">
        <span class="logo-mini"><b>C</b>oder</span>
        <span class="logo-lg">Coder<b>-</b>Dojo</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>
        <!-- Navbar Right Menu -->
        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="https://placehold.it/160x160" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{ user.get_short_name }}.</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="https://placehold.it/160x160" class="img-circle" alt="User Image">

                            <p>
                                {{ user }}
                                <small>{{ user.family }}</small>
                            </p>
                        </li>
                        <!-- Menu Body
                        <li class="user-body">
                          <div class="row">
                            <div class="col-xs-4 text-center">
                              <a href="#">Followers</a>
                            </div>
                            <div class="col-xs-4 text-center">
                              <a href="#">Sales</a>
                            </div>
                            <div class="col-xs-4 text-center">
                              <a href="#">Friends</a>
                            </div>
                          </div>

                        </li> /.row -->
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="{% url 'dashboard:index' %}" class="btn btn-default btn-flat">Utilisateurs</a>
                            </div>
                            <div class="pull-right">
                                <a href="{% url 'core:logout' %}" class="btn btn-default btn-flat">Se déconnecter</a>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button
                <li>
                  <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>
                </li>-->
            </ul>
        </div>

    </nav>
</header>

Dashboard/templates/Dashboard/index.html
{% extends 'Dashboard/layout.html' %}
{% block body %}
    <div class="callout callout-danger">
    <h4>Site encore en Développement</h4>
    <p>Si vous rencontrer un problème ou un bug ou juste une proposition de fonctionalité, <a
            href="mailto:contact@tchekda.fr">Contactez moi par Mail</a>. Merci d'avance</p>
    </div>
{% endblock %}

Dashboard/templates/Dashboard/sidebar.html
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="https://placehold.it/160x160" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{ user.get_full_name }}</p>
                <i class="fa fa-circle text-success"></i> {{ user.get_type_display }}
            </div>
        </div>
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header"><a href="{% url 'dashboard:index' %}" class="no-border no-padding">Page d'Accueil</a>
            </li>
            <li class="active treeview menu-open">
                <a href="#">
                    <i class="fa fa-calendar"></i> <span>Évènenement</span>
                    <span class="pull-right-container">
                        <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li {% if past == False %}class="active"{% endif %}><a href="{% url 'dashboard:futur-events' %}"><i
                            class="fa fa-calendar-check-o"></i> Prochains évènements</a></li>
                    <li {% if past %}class="active"{% endif %}><a href="{% url 'dashboard:past-events' %}"><i
                            class="fa fa-calendar-times-o"></i> Évènenements passés</a></li>
                    {% if user.is_staff %}
                        <li><a href="{% url 'dashboard:add-event' %}"><i
                                class="fa fa-plus"></i> Créer un évènement</a></li>
                    {% endif %}
                </ul>
            </li>
            {% if workshops %}
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-laptop"></i>
                        <span>Ateliers</span>
                        <span class="pull-right-container">
                          <span class="label label-primary pull-right">{{ workshops.count }}</span>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        {% for workshop in workshops %}
                            <li><a href="{% url 'dashboard:workshops' workshop.id %}"><i
                                    class="fa fa-circle-o"></i> {{ workshop }}</a></li>
                        {% endfor %}
                        {% if user.type == 'STA' or user.is_staff %}
                            <li><a href="{% url 'dashboard:add-workshop' %}"><i
                                    class="fa fa-plus"></i> Créer un Workshop</a></li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
            {% if family %}
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-users"></i>
                        <span>Famille</span>
                        <span class="pull-right-container">
                            {% if user.type == 'STA' and families %}
                                <span class="pull-right-container">
                                  <span class="label label-primary pull-right">{{ families.count }}</span>
                                </span>
                            {% else %}
                                <i class="fa fa-angle-left pull-right"></i>
                            {% endif %}
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li class="treeview">
                            <a href="#">
                                <span>Ma Famille</span>
                                <span class="pull-right-container">
                                    <span class="label label-success pull-right">{{ family.count }}</span>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                {% for familyUser in family %}
                                    {% if user.id == familyUser.id %}
                                        <li class="active"><a href="{% url 'dashboard:user-edit' familyUser.id %}"><i
                                                class="fa fa-circle-o"></i> {{ familyUser }}</a></li>
                                    {% else %}
                                        <li><a href="{% url 'dashboard:user' familyUser.id %}"><i
                                                class="fa fa-circle-o"></i> {{ familyUser }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                <li><a href="{% url 'dashboard:add-member' %}"><i
                                        class="fa fa-plus"></i> Ajouter un membre</a></li>
                                <li><a href="{% url 'dashboard:edit-family' family.0.family.id %}"><i
                                        class="fa fa-edit"></i> Editer les Informations</a></li>
                            </ul>
                        </li>
                        {% if user.is_staff and families %}
                            <li>
                                <a href="{% url 'dashboard:families' %}"><i class="fa fa-search"></i> Trouver une
                                    famille</a>
                            </li>
                        {% endif %}
                    </ul>
                </li>
            {% endif %}
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-users"></i>
                    <span>Invitations</span>
                    <span class="pull-right-container">
                                <span class="pull-right-container">
                                  <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </span>
                </a>
                <ul class="treeview-menu">
                    <li>
                        <a href="{% url 'dashboard:invitations' %}"><i class="fa fa-circle-o"></i> Mes Invitations</a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:new-invite' %}"><i class="fa fa-envelope-o"></i> Envoyer une
                            invitation</a>
                    </li>
                </ul>
            </li>
            {% if user.is_staff %}
                <li class="treeview">
                    <a href="#">
                        <i class="fa fa-lock"></i>
                        <span>Administration</span>
                        <span class="pull-right-container">
                                <span class="pull-right-container">
                                  <i class="fa fa-angle-left pull-right"></i>
                                </span>
                        </span>
                    </a>
                    <ul class="treeview-menu">
                        <li>
                            <a href="{% url 'dashboard:edition-list' %}"><i class="fa fa-edit"></i> Editer les textes</a>
                        </li>
                        <li>
                            <a href="/admin/" target="_blank"><i class="fa fa-circle-o"></i> Admin Django</a>
                        </li>
                    </ul>
                </li>
            {% endif %}
        </ul>
    </section>

</aside>